Keter/Main.hs
Having option for sub-folders allows for easier management of bundles eg. keep different domains in different folders.
I need it to sanely set-up git-annex to sync files to my remote servers.
=> Allow incoming folder to contains subfolders

Keter/Main.hs, Keter/Proxy.hs, Keter/Types/V04.hs, Keter/Types/V10.hs, etc/keter-config.yaml
@snoyberg , ok, it seems I've done. Please review, I can remove last two commits. Also I didn't bumped version, because I'm not sure is it breaking change or not.
=> Configurable time bound

.gitignore, .travis.yml
I'll merge this on successful travis build.
=> Update travis build for GHC-7.10, add stack build artifacts to gitignore.

ChangeLog.md, keter.cabal
* Update changelog with default connection time bound fix.
=> Bump version to 1.4.2.1.

Keter/Types/Common.hs
Not exactly sure if the constructor is a part of the external interface though.
=> spelling fix for Forgeting

ChangeLog.md, keter.cabal
Testing this pull request against Travis build. If it passes I'm pushing the new version to Hackage. Fixes #116
=> Bumping Version to 1.4.3

Keter/Main.hs
Missed one. Will wait for the build again.
=> Replace MIN_VERSION macro SYSTEM_FILEPATH.

packaging/mkketerdeb.sh
This PR fixes the deb packaging script for upstart
=> Fix deb packaging script for Upstart (Ubuntu)

setup-keter.sh
=> Update setup-keter.sh to use stack

Keter/LabelMap.hs, test/LabelMapSpec.hs
revert 5e857eb and cb50d58 in Keter/LabelMap.hs
=> Fix wildcards

Data/Conduit/Process/Unix.hs, Network/HTTP/ReverseProxy/Rewrite.hs
A stab at fixing https://github.com/snoyberg/keter/issues/147
I am not sure about `new_session = True`  but otherwise works with the latest `lts` and `nightly`
=> Add new CPP for fields introduced in process 1.3 and 1.4

README.md
Add `[Install]` section so it can be *enabled* and auto started on boot
=> Fix systemd unit service

setup-keter.sh
Since version 15.04 Ubuntu changed from Upstart to systemd. I changed the service configuration in the `setup-keter.sh` script accordingly.
=> Changed configuration of keter service from Upstart to systemd.

ChangeLog.md
I just inspected the git log to find them
=> Add chagnes since last release to changelog

ChangeLog.md, keter.cabal
Apparantly we need to be at least cabal 1.10.
Also adds some additional changelog lines.
=> Fix upload to hackage issues

.github/workflows/stack.yaml
doesn't work for some reason.
Again if someone can make this work send a PR.
=> Drop support for lts-16 for osx

ChangeLog.md, Data/Aeson/KeyHelper.hs, Data/Yaml/FilePath.hs, Keter/Plugin/Postgres.hs, Keter/Types/Middleware.hs, Keter/Types/V10.hs, keter.cabal
Hi, I just have a look at your  `yaml` package and change `keter` along with it.
now I can compile the `keter` via cabal
=> minor tweaks for aeson 2

ChangeLog.md
Group the aeson key changes under 1.7
I think it's best to keep these versions
simple, since we added a module it should
be a minor release.
=> Fixup versions in changelog

.github/workflows/nix.yaml, nix/pin.nix, shell.nix
This provides a basic nix shell with cabal
and a pin.
It's pretty much cabal2nix . --shell
=> Add nix shell

ChangeLog.md, keter.cabal
=> Add better description in cabal file instead of an omnious warning

ChangeLog.md, Keter/Main.hs, Keter/Proxy.hs, Keter/Types/Common.hs, Keter/Types/V10.hs, etc/keter-config.yaml
serves a default or custom error response if it occurs.
Emits the exception to the log.
=> Squash proxy exceptions if they occur

ChangeLog.md, keter.cabal, src/Keter/Main.hs, src/Keter/Plugin/Postgres.hs, src/Keter/Proxy.hs, src/Keter/Types/V04.hs, src/Keter/Types/V10.hs, src/Network/HTTP/ReverseProxy/Rewrite.hs, src/main/keter.hs
This pull request removes all `Default` instances within the code and replaces them with named functions. Not all `def`s are removed, as some are imported from different packages and modules such as `Network.Wai.Middleware.Gzip`.
=> Removed 'default', the package.

ChangeLog.md, keter.cabal, src/Keter/Aeson/KeyHelper.hs, src/Keter/App.hs, src/Keter/Conduit/LogFile.hs, src/Keter/Conduit/Process/Unix.hs, src/Keter/Main.hs, src/Keter/Plugin/Postgres.hs, src/Keter/Types/Common.hs, src/Keter/Types/Middleware.hs, src/Keter/Types/V04.hs, src/Keter/Types/V10.hs, src/Keter/Yaml/FilePath.hs
This was supposed to be a more difficult task.
=> Renamed all "Data" modules to "Keter" modules.

.github/workflows/nix.yaml, default.nix, incoming/foo/hello.hs, incoming/foo1_0/hello.hs, incoming/websockets/chat.hs, nix/pin.nix, nix/pkgs.nix, shell.nix
This also closes https://github.com/snoyberg/keter/issues/263
Now I can run tests again
=> Add better nix infrastructure that doesn't need to be kept up to date with cabal file

ChangeLog.md, keter.cabal, src/Keter/Logger.hs
=> fixes #288, set log backup number to 20

keter.cabal, src/Keter/App.hs, src/Keter/AppManager.hs, src/Keter/Main.hs, src/Keter/SharedData/App.hs, src/Keter/SharedData/AppManager.hs, vm.nix
=> Fix reloading stuck on crash-looping bundles
