- Keter/Proxy.hs
- Keter/Types/V10.hs
- keter.cabal
Add support for chain certificates. This PR depends on yesodweb/wai#349 which adds chain certificate support to warp-tls. This PR takes a wild guess and sets the dependency bound on warp-tls to >= 3.0.2.1.
> Support chain certificates in credentials

- keter.cabal
As discussed in #83, the dependency on network-conduit-tls now seems unused. keter built fine for me without it.
> network-conduit-tls is no longer needed.

- Keter/Plugin/Postgres.hs
Lowercase appname when generating db name in postgres plugin
Branch made from issue #86 
supersede pr #87
also applied Hlint suggestion
- remove redundant `do`
- merge two imports statements into one
> lowercase app name when generating postgres db name

- ChangeLog.md
- Codec/Archive/TempTarball.hs
- Data/Yaml/FilePath.hs
- Keter/App.hs
- Keter/AppManager.hs
- Keter/Main.hs
- Keter/Plugin/Postgres.hs
- Keter/Proxy.hs
- Keter/Types/Common.hs
- Keter/Types/V04.hs
- Keter/Types/V10.hs
- keter.cabal
- main/keter.hs
Add configurable time-outs.
This allows to override time-outs for specific bundles.
It uses modified `http-reverse-proxy` package. Where it moves handling time-outs there. Bonus is the web-socket handling is a bit better.
Time-outs on static files will allow to 'stream' big files. 
Add `middleware` to `reverse-proxy` stanza
This allows to add e.g `basic auth` to reversed hosts or maybe modify headers.
> Add configurable timeouts

- Keter/App.hs
- Keter/Proxy.hs
This PR is incomplete, because I think the warnings only apply to a particular version of GHC, and the changes may not be backward compatible. I'm on 7.8.4 and don't have a quick way to try earlier versions.
> Appease redundant import warnings

- stack.yaml
Not sure 2.11 is appropriate, but pull-requesting for the fun of it. Note
the necessity of putting wai-app-static-3.1.0 as an extra-dep.
> Add stack.yaml using LTS 2.11

- Keter/Plugin/Postgres.hs
- README.md
- incoming/foo1_0/config/keter.yaml
- keter.cabal
#100 
Keter can manage a remote DB server, based on app settings. I believe it should be backwards compatible with existing postgres.yaml files, so I think only a minor version bump is necessary. 
This doesn't deal with the issue @ygale raised; it actually compounds the issue, as now there are more assumptions about postgres's setup. There are a few issues which might need to be decided before this is merged:
* The assumptions regarding how the remote DB server has been setup; specifically, the `trust` method note. Is it worth taking the time to try to allow for a username / password to be set in the app's settings? As a general rule, I don't like requiring plain-text passwords. 
* As I noted in the readme, if an app is changed to use a different server, but said app already exists in the …
> Remote postgres

- Keter/App.hs
- Keter/Types/V10.hs
- incoming/foo1_0/config/keter.yaml
Give background tasks a forward-env option, and also pass through the
environment variables specified in the keter config.
> Env options for background tasks

- Keter/Main.hs
- Keter/Types/V04.hs
- Keter/Types/V10.hs
@geraldus 
@tolysz 
I believe there was a small issue with the 5 minute calculation, I couldn't find anywhere that explicitly states that the value is in microseconds but after some discussion on IRC and further testing I believe this is correct.
> Change default connection time bound calculation from 5s to 5min.

- Keter/Main.hs
- keter.cabal
Newer versions of fsnotify avoid the need for encodeString. Prior to this change, I couldn't get keter to build on FreeBSD with ghc 7.10.1
> Use newer fsnotify to avoid system-filepath

- ChangeLog.md
- Keter/Main.hs
- keter.cabal
@snoyberg I tested against lts-2.1. lts-2.2 still has issues with http-reverse-proxy.
> Add filesystem-path compatibility for older fsnotify versions.

- packaging/mkketerdeb.sh
- stack.yaml
This PR provides support for building a keter deb package using either stack or cabal. It also updates stack.yaml to use the latest LTS version.
> Add stack support

- .travis.yml
- Keter/App.hs
- Keter/HostManager.hs
- Keter/Proxy.hs
- Keter/Types.hs
- Keter/Types/V10.hs
- incoming/foo1_0/config/keter.yaml
- keter.cabal
- stack.yaml
Keter is created for hosting multiple apps; but all certificates need to be bundled together as one.
This patch adds possibility to have a different certificate per webapp... extending other stanzas should be as easy as that one.
PR is complete, however if someone have time to extend it to other parts (i.e. not just webapps)
And allow loading certificates require absolute paths (I placed various todos so feel free to pick them up).
> Initial implementation of SNI.

- README.md
Added explanation of how to make multiple SSL certs work per Yesod App, which is probably the easier way to deal with the multiple domains on one keter problem.
> Updated README.md - Multiple SSL Certs

- README.md
The `Setup` part for Redhat and derivatives distributions requires using the `dnf` package manager, but more important, it requires creating a `Systemd` service unit
> Add Redhat and derivatives setup instructions

- Keter/Proxy.hs
- stack.yaml
i.e. serving `bla` use pre-compressed version `bla.gz` if present saving cpu.
> Use better gzip default setting

- README.md
Ubuntu uses systemd for version 15.04 and greater as default now.
> Update readme for systemd being used in ubuntu

- Keter/Proxy.hs
This patch allows keter to be compatible with http-reverse-proxy 0.6.0, without losing compatibility with earlier versions of http-reverse-proxy.
> Allow http-reverse-proxy 0.6.0

- README.md
I myself was very confused about how this worked, I kept looking for
configuration options for setting an http endpoint.
But after inspecting the code I realized it was basically doing a
`nc` on the port.
-- squash log
Move health check lower
> Add better explanation of health check to the readme.

- keter.cabal
process 1.6.8 -> 1.7 (note that process uses 4, however the final
number seems to be ignored)
wai-extra 3.1 -> 3.2
Last time this happened was 6 years ago.
> Bump version bounds

- Keter/App.hs
- Keter/AppManager.hs
- Keter/Types/Common.hs
- Keter/Types/V10.hs
It took me the longest time to figure out why keter wasn't
reloading properly (It trashed the old app while an erronous new one
was attempted to be loaded),
only after adding log messages like these, I realized
keter was actually rebooted with systemd (reload from nothing).
This was my own fault, however I think adding these log messages
would help speed up future debug sessions for other users.
This also adds several show instances to basic types in support of
this logging.
> Add aditional log messages to keter reloading logic.

- keter.cabal
In version 3.3.0 warp-tls introduced a breaking change removing `WarpTLS.keyFile` and `WarpTLS.certFile` which are still used in keter. Until keter migrates to the intended API, requiring a lower version is necessary.
I also tried fixing it to use the current API and I think I succeeded in Types/V04.hs but I was not able fix the reading access in Types/V10.hs to these accessors.
> Require warp-tls < 3.3.0

- Keter/App.hs
- Keter/Types/Common.hs
- Keter/Types/V10.hs
- incoming/Makefile
- incoming/nc/Readme.md
- incoming/nc/config/keter.yaml
- incoming/nc/nc.sh
This allows certain application to have a long boot cycle while the
old application is still running.
A specific use case for supercede for example is running migrations
before switching.
fixes: https://github.com/snoyberg/keter/issues/218
-- squash log
Add comment it's in microseconds
Fix import styling
> Add configurable timeout for ensure alive

- Keter/Types/V04.hs
- Keter/Types/V10.hs
- keter.cabal
No need to construct full TLSSettings in V04 TLSConfig, only to later extract certKey, certFile and tlsSessionManagerConfig from there when converting to V10. Simply keep certKey, certFile and tlsSessionManagerConfig in TLSConfig. This will allow usage of warp-tls 3.3 in Keter which was restricted in #213. With this change we don't need yesodweb/wai#841.
> Simplify V04.TLSConfig to be compatible with warp-tls update.

- .github/workflows/stack.yaml
Travis stopped building for some reason.
I asked around and it turns out it's not
secure and only for paying customers:
https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/
> Attempt add github action.

- .github/workflows/stack.yaml
- ChangeLog.md
- Data/Conduit/Process/Unix.hs
- Keter/App.hs
- Keter/AppManager.hs
- Keter/Cli.hs
- Keter/Main.hs
- Keter/Types/Common.hs
- Keter/Types/V10.hs
- keter.cabal
* Make keter more chatty on boot.
This allows you to figure out in code where things go wrong.
* Add opt-in debug CLI, allowing you to inspect keters' internal state.
You can activate it by specifying a cli-port.
* Emit which pid is being killed by keter.
This helps with process leakage issues,
for example if the user launches from a bash script without using `exec`.
> Add optional debug cli, add a lot more logging

- ChangeLog.md
- Keter/Main.hs
- Keter/Proxy.hs
- Keter/Types/V10.hs
- etc/keter-config.yaml
- incoming/Makefile
+ [x] still need to test
I tested unkown host with:
```
nc localhost 8080
GET / HTTP/1.0
```
No host was added.
where blah wasn't a running host (only the nc example ran on localhost)
The other response we can get with:
```
nc localhost 8080
GET / HTTP/1.0
HOST: blah
```
The other one is quite easy by running keter with no hosts
(so just deleting all .keter files in incoming
+ [x] update changelog
+ [ ] make release
Implements: https://github.com/snoyberg/keter/issues/217
> Add config to replace welcome to keter screen with custom page 

- ChangeLog.md
- Keter/Proxy.hs
- keter.cabal
The host field can be spoofed,
which allows an xss attack.
Eg you can put a bunch of javascript
(or whatever html) in the hostfield and
response to trick the user.
These chagnes make that impossible.
add changelog, bump cabal
> Fix potential xss issue in missing host response

- ChangeLog.md
- Keter/Proxy.hs
- keter.cabal
It seems unlikely an attacker will actually manage
to insert a line break at that point.
But since this isn't a common code path.
We may as well escape it for HTML.
> Escape X-Forwarded-Host header as well

- ChangeLog.md
- Keter/Proxy.hs
- keter.cabal
We got a dedicated status code for this (502).
If a host is not found we now return 404.
Before this was 200 status codes (ok, which it's not)
pages even though hosts were missing!
This should make writing tests easier and make
monitoring systems more alert.
Update changelog
bump version
> Add proper status codes to error host responses

- ChangeLog.md
- nix/config.nix
under load this becomes an issue.
I'm unsure why it crashed, most likely systemd decided
to send it a sigterm signal.
This is the config nginx uses as well.
> change nix config to always restart keter

- ChangeLog.md
- Keter/Plugin/Postgres.hs
- keter.cabal
Closes #238. I ended up having to deal with other issues, which caused this to be delayed. 
The solution I choose was to  annotate the IOException with a better error message directly inside the postgres plugin. Since I am annotating the exception in the postgres plugin, when sudo is used in other places it won't use this message. 
Another possible solution is to create a custom KeterException for missing sudo, and then throw that when we get the missing sudo IOException. The advantage of that is that we can reuse the exception in all the places where we get an error because we are missing sudo, the downside is in adding more coding, and creating a custom KeterException when we don't necessarily need one.
> Better error messages for missing sudo when attempting psql connection

- src/Keter/App.hs
- src/Keter/Conduit/Process/Unix.hs
This PR changes `processMonitor` to be defined in terms of some `MonadLogger m`, so we can use TH logging splices like every other module in keter and achieve consistent formatting via the main logger. 
Previously, there was a TODO comment above `processMonitor` suggesting it be refactored to use `KeterM`; however the `Keter.Conduit.Process.Unix` module could otherwise be packaged independently of `keter` in the future and I did not want to unnecessarily tightly couple it with the rest of `keter` as such. By defining it in terms of some polymorphic `MonadLogger m`, we can specialize `processMonitor` to `KeterM` to be used in the rest of `keter`, but still allow for flexibility to be specialized to other logging contexts should it ever be packaged independently in the future. 
With this …
> Make `processMonitor` logging consistent with the rest of `keter` logs

- ChangeLog.md
- MigrationGuide-2.1.md
- README.md
This PR adds a short and to-the-point migration guide for anyone planning on upgrading to `keter` 2.1, especially in a production setting.
The guide covers:
- What breaking changes to be aware of
- Examples of said changes
- Solutions/workaround to address said changes
- New features people may wish to consider, which may subsume the need to fix said breaking changes in the first place
A note was also added in the changelog to reference the migration guide for more information on any of the above.
> Migration Guide for 2.1

- ChangeLog.md
- etc/keter-config.yaml
- keter.cabal
- src/Keter/Config/V10.hs
- src/Keter/Proxy.hs
- test/Spec.hs
Hi again,
Here's another patch I'm trying to unvendor, as it seems universally useful to any user of keter.
The motivating problem is:
* AWS LB TG healthcheck cannot currently be made to send any custom Host header. It always sends the target's (keter's) IP address in there, e.g. `Host: 172.30.131.18`.
Together with vhosting, this makes it impossible to healthcheck¹ individual webapps running under keter.
¹ *healthcheck from AWS TG* more specifically; still doable with other monitoring systems.
--------------------
Have a partial remedy with a `/keter-health` endpoint, that if enabled always responds with status 200.
For sake of explicitness, there's no hardcoded fallback for the path — if absent from config, the feature is disabled. If enabled in config, that same config explicitly …
> Add config "healthcheck-path" to respond 200 on

- .github/workflows/nix.yaml
- ChangeLog.md
- keter.cabal
- nix/pin.nix
- nix/pkgs.nix
add lower limit for tar to 0.6.0.0, which fixes "FileNotExecutable" bug. see #291, special thanks to @scheottl for finding and debugging.
> Fix old tar breaking keter

- keter.cabal
- src/Keter/Aeson/KeyHelper.hs
- src/Keter/Conduit/Process/Unix.hs
- src/Keter/Main.hs
- src/Keter/Proxy.hs
- src/Keter/Rewrite.hs
The project used CPP to conditionally support legacy packages. It's time to drop support for these, which means we no longer need to use CPP, nor the system-filepath cabal flag.
This also raises the lower bound for `process` to 1.6.
---
Worked on this during https://github.com/Thaigersprint/thaigersprint-2025/issues/1.
> Remove CPP

- keter.cabal
This dependency was conditional on GHC 7.6 or earlier, which is now ancient. We can just remove it.
> Remove ghc-prim

- .gitignore
- flake.nix
- keter.nix
- vm.nix
This is a first pass at adding integrated tests for keter. This works by spinning up a NixOS virtual machine, running keter as a systemd service on it, and probing it with HTTP requests.
This work brings us closer to resolving https://github.com/snoyberg/keter/issues/258.
---
Working on this during https://github.com/Thaigersprint/thaigersprint-2025/issues/1.
> Add first integrated test with nixosTest VM

- src/Keter/App.hs
Fixing of issue https://github.com/snoyberg/keter/issues/296 "Reloading is broken in v2.1 with rotate-logs: True"
> Fixing reloading when rotate-logs is true

- vm.nix
This is the follow-up to [this PR][0].
[0]: https://github.com/snoyberg/keter/pull/308
/cc @ulidtko @ktak-007
> Add integrated test for log rotation
